window.LOUDFIT_UNITS = [
  {
    name: "Carreco Curvalinhos",
    slug: "carreco-curvalinhos",
    city: "",
    district: "Curvalinhos",
    address: "Endereço em atualização",
    hours: "Horários em atualização",
    whatsapp: "#",
    whatsapp_url: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "unidades/carreco-curvalinhos/#matricula",
    plans_available: true,
    detail_url: "unidades/carreco-curvalinhos/",
    image: "../assets/images/loudfit-real-studio.jpg",
    structure: ["Musculação", "Cardio", "Ambiente climatizado", "Atendimento presencial"],
    modalities: ["Musculação", "Cardio", "Funcional"]
  },
  {
    name: "Mogi Mirim",
    slug: "mogi-mirim",
    city: "Mogi Mirim",
    district: "",
    address: "Endereço em atualização",
    hours: "Horários em atualização",
    whatsapp: "#",
    whatsapp_url: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "#matricula-em-breve",
    plans_available: true,
    image: "../assets/images/loudfit-real-machines.jpg",
    structure: ["Musculação", "Cardio", "Equipamentos fortes", "Equipe local"],
    modalities: ["Musculação", "Cardio"]
  },
  {
    name: "Anchieta",
    slug: "anchieta",
    city: "",
    district: "Anchieta",
    address: "Endereço em atualização",
    hours: "Horários em atualização",
    whatsapp: "#",
    whatsapp_url: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "#matricula-em-breve",
    plans_available: true,
    image: "../assets/images/loudfit-real-weights.jpg",
    structure: ["Musculação", "Cardio", "Área de pesos", "Acompanhamento local"],
    modalities: ["Musculação", "Cardio", "Funcional"]
  },
  {
    name: "Moreiras",
    slug: "moreiras",
    city: "",
    district: "Moreiras",
    address: "Endereço em atualização",
    hours: "Horários em atualização",
    whatsapp: "#",
    whatsapp_url: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "#matricula-em-breve",
    plans_available: true,
    image: "../assets/images/loudfit-real-facade.jpg",
    structure: ["Musculação", "Cardio", "Fachada de alto impacto", "Rotina de bairro"],
    modalities: ["Musculação", "Cardio"]
  },
  {
    name: "Ribeirão Industrial",
    slug: "ribeirao-industrial",
    city: "Ribeirão",
    district: "Industrial",
    address: "Endereço em atualização",
    hours: "Horários em atualização",
    whatsapp: "#",
    whatsapp_url: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "#matricula-em-breve",
    plans_available: true,
    image: "../assets/images/loudfit-real-machines.jpg",
    structure: ["Musculação", "Cardio", "Sala equipada", "Presença local"],
    modalities: ["Musculação", "Cardio", "Funcional"]
  },
  {
    name: "Nova unidade LoudFit",
    slug: "sexta-unidade",
    city: "",
    district: "Em implantação",
    address: "Endereço em definição",
    hours: "Abertura em breve",
    whatsapp: "#",
    whatsapp_url: "#",
    instagram: "#",
    opening_url: "#acompanhar-abertura",
    status: "em_inauguracao",
    statusLabel: "Em implantação",
    badge: "Implantação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: false,
    checkout_url: "",
    plans_available: false,
    image: "../assets/images/real-opening.jpg",
    structure: ["Implantação em curso", "Padrão LoudFit", "Comunicação local"],
    modalities: ["Musculação", "Cardio"]
  }
];
