window.LOUDFIT_UNITS = [
  {
    name: "Carreco Curvalinhos",
    slug: "carreco-curvalinhos",
    city: "",
    district: "Curvalinhos",
    address: "",
    hours: "",
    whatsapp: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    image: "../assets/images/loudfit-real-studio.jpg"
  },
  {
    name: "Mogi Mirim",
    slug: "mogi-mirim",
    city: "Mogi Mirim",
    district: "",
    address: "",
    hours: "",
    whatsapp: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    image: "../assets/images/loudfit-real-machines.jpg"
  },
  {
    name: "Anchieta",
    slug: "anchieta",
    city: "",
    district: "Anchieta",
    address: "",
    hours: "",
    whatsapp: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    image: "../assets/images/loudfit-real-weights.jpg"
  },
  {
    name: "Moreiras",
    slug: "moreiras",
    city: "",
    district: "Moreiras",
    address: "",
    hours: "",
    whatsapp: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    image: "../assets/images/loudfit-real-facade.jpg"
  },
  {
    name: "Ribeirao Industrial",
    slug: "ribeirao-industrial",
    city: "Ribeirao",
    district: "Industrial",
    address: "",
    hours: "",
    whatsapp: "#",
    instagram: "#",
    status: "em_operacao",
    statusLabel: "Em operação",
    image: "../assets/images/loudfit-real-machines.jpg"
  },
  {
    name: "6ª Unidade LoudFit",
    slug: "sexta-unidade",
    city: "",
    district: "Em inauguração",
    address: "",
    hours: "",
    whatsapp: "#",
    instagram: "#",
    status: "em_inauguracao",
    statusLabel: "Em inauguração",
    badge: "6ª unidade",
    image: "../assets/images/real-opening.jpg"
  }
];
