window.LOUDFIT_UNITS = [
  {
    name: "LoudFit Carrefour Valinhos",
    shortName: "Carrefour Valinhos",
    slug: "carreco-curvalinhos",
    city: "Valinhos",
    state: "SP",
    district: "Carrefour Valinhos",
    address: "",
    hours: "",
    phone: "",
    cep: "",
    whatsapp: "",
    whatsapp_url: "",
    instagram: "",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "unidades/carreco-curvalinhos/#matricula",
    plans_available: true,
    plans_type: "standard",
    detail_url: "unidades/carreco-curvalinhos/",
    image: "../assets/images/loudfit-real-studio.jpg",
    structure: ["Musculação", "Cardio", "Ambiente climatizado", "Atendimento presencial"],
    modalities: ["Musculação", "Cardio", "Funcional"]
  },
  {
    name: "LoudFit Ipiranga",
    shortName: "Ipiranga",
    slug: "ipiranga",
    city: "São Paulo",
    state: "SP",
    district: "Ipiranga",
    address: "R. Lino Coutinho, 385 - Ipiranga, São Paulo - SP",
    hours: "",
    phone: "",
    cep: "",
    whatsapp: "",
    whatsapp_url: "",
    instagram: "",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "unidades/ipiranga/#matricula",
    plans_available: true,
    plans_type: "ipiranga",
    detail_url: "unidades/ipiranga/",
    image: "../assets/images/loudfit-real-machines.jpg",
    structure: ["Musculação", "Cardio", "Equipamentos fortes", "Equipe local"],
    modalities: ["Musculação", "Cardio"]
  },
  {
    name: "LoudFit Anchieta",
    shortName: "Anchieta SP",
    slug: "anchieta",
    city: "São Paulo",
    state: "SP",
    district: "Vila Moinho Velho",
    address: "Rod. Anchieta, 1778 - Vila Moinho Velho, São Paulo - SP",
    hours: "",
    phone: "",
    cep: "",
    whatsapp: "",
    whatsapp_url: "",
    instagram: "",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "unidades/#matricula-em-breve",
    plans_available: true,
    plans_type: "standard",
    image: "../assets/images/loudfit-real-weights.jpg",
    structure: ["Musculação", "Cardio", "Área de pesos", "Acompanhamento local"],
    modalities: ["Musculação", "Cardio", "Funcional"]
  },
  {
    name: "LoudFit Amoreiras",
    shortName: "Amoreiras",
    slug: "amoreiras",
    city: "Campinas",
    state: "SP",
    district: "Amoreiras",
    address: "",
    hours: "",
    phone: "",
    cep: "",
    whatsapp: "",
    whatsapp_url: "",
    instagram: "",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "unidades/#matricula-em-breve",
    plans_available: true,
    plans_type: "standard",
    image: "../assets/images/loudfit-real-facade.jpg",
    structure: ["Musculação", "Cardio", "Fachada de alto impacto", "Rotina de bairro"],
    modalities: ["Musculação", "Cardio"]
  },
  {
    name: "LoudFit Vila Industrial",
    shortName: "Vila Industrial",
    slug: "vila-industrial",
    city: "Campinas",
    state: "SP",
    district: "Vila Industrial",
    address: "",
    hours: "",
    phone: "",
    cep: "",
    whatsapp: "",
    whatsapp_url: "",
    instagram: "https://www.instagram.com/loudfit.vilaindustrial/",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "unidades/#matricula-em-breve",
    plans_available: true,
    plans_type: "standard",
    image: "../assets/images/loudfit-real-machines.jpg",
    structure: ["Musculação", "Cardio", "Sala equipada", "Presença local"],
    modalities: ["Musculação", "Cardio", "Funcional"]
  },
  {
    name: "LoudFit Mogi Mirim",
    shortName: "Mogi Mirim",
    slug: "mogi-mirim",
    city: "Mogi Mirim",
    state: "SP",
    district: "Mogi Mirim",
    address: "",
    hours: "",
    phone: "",
    cep: "",
    whatsapp: "",
    whatsapp_url: "",
    instagram: "",
    status: "em_operacao",
    statusLabel: "Em operação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: true,
    checkout_url: "unidades/#matricula-em-breve",
    plans_available: true,
    plans_type: "standard",
    image: "../assets/images/loudfit-real-studio.jpg",
    structure: ["Musculação", "Cardio", "Estrutura LoudFit", "Atendimento presencial"],
    modalities: ["Musculação", "Cardio", "Funcional"]
  },
  {
    name: "Nova unidade LoudFit",
    shortName: "Nova unidade",
    slug: "sexta-unidade",
    city: "",
    state: "",
    district: "Em implantação",
    locationLabel: "Em implantação",
    address: "",
    hours: "Abertura em breve",
    phone: "",
    cep: "",
    whatsapp: "",
    whatsapp_url: "",
    instagram: "",
    opening_url: "unidades/#acompanhar-abertura",
    status: "em_inauguracao",
    statusLabel: "Em implantação",
    badge: "Implantação",
    type: "propria",
    typeLabel: "Unidade própria",
    checkout_enabled: false,
    checkout_url: "",
    plans_available: false,
    plans_type: "standard",
    image: "../assets/images/real-opening.jpg",
    structure: ["Implantação em curso", "Padrão LoudFit", "Comunicação local"],
    modalities: ["Musculação", "Cardio"]
  }
];
